### ISSUE TITLE
Power matching 

### ISSUE THREAD

**Issue by hupodexofan** [baldsealion/BSL-Tools-ROG-ALLY-Edition#1]
The app does not save when ticking off the boxes to enable power matching for un-plugged.

when opening the menu the boxes are untick again. 

V1.0.7

**Comment by baldsealion** [comment]
This is actually by design. The checkbox windows will always show you the default values, not what you currently have set them to. You can verify it is working when you toggle the profile to see if power matching is enabled or not.
